name: Terraform Security Scan

on: [push, pull_request]

jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Terraform security scan
        uses: triat/terraform-security-scan@v2.2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
